SEEDED_CODES = [
    {
        "code": "P0300",
        "title": "Random or Multiple Cylinder Misfire",
        "explanation": "Your car is reporting misfires that may be happening across more than one cylinder. That usually means fuel is not burning smoothly, and the cause can range from ignition parts to fuel delivery or air leaks.",
        "urgency": "high",
        "drive_safety": "caution",
        "likely_causes": ["Worn spark plugs", "Weak ignition coils", "Vacuum leak", "Fuel delivery issue", "Low compression"],
        "repair_paths": ["Inspect spark plugs and coils", "Check for vacuum leaks", "Test fuel pressure", "Run compression or leakdown testing if misfire persists"],
        "cost_range": "$120-$1,200+ depending on root cause",
        "mechanic_questions": ["Which cylinders are misfiring in live data?", "Can you show me the spark plug or coil test result?", "Did you check fuel pressure and vacuum leaks before recommending major repairs?"],
        "category": "engine",
    },
    {
        "code": "P0301",
        "title": "Cylinder 1 Misfire",
        "explanation": "Your car is reporting a cylinder 1 misfire. That may mean this cylinder is not burning fuel properly, often because of an ignition, fuel, airflow, or compression issue.",
        "urgency": "high",
        "drive_safety": "caution",
        "likely_causes": ["Spark plug wear", "Faulty ignition coil", "Fuel injector issue", "Vacuum leak near cylinder 1", "Compression problem"],
        "repair_paths": ["Swap coil with another cylinder to see if the misfire follows", "Inspect spark plug condition", "Test injector operation", "Check compression if basic checks pass"],
        "cost_range": "$100-$900+ depending on parts and testing",
        "mechanic_questions": ["Did the misfire follow the coil or plug when swapped?", "Can I see the old spark plug condition?", "Was compression checked before deeper engine work was recommended?"],
        "category": "engine",
    },
    {
        "code": "P0302",
        "title": "Cylinder 2 Misfire",
        "explanation": "Your car is reporting a cylinder 2 misfire. That usually means this cylinder is not burning fuel properly. Common causes include a worn spark plug, faulty ignition coil, injector issue, or airflow/fuel delivery problem.",
        "urgency": "high",
        "drive_safety": "caution",
        "likely_causes": ["Worn spark plug", "Faulty ignition coil", "Fuel injector issue", "Vacuum leak", "Low compression"],
        "repair_paths": ["Inspect or replace spark plug", "Swap/test ignition coil", "Check injector pulse and fuel delivery", "Perform compression testing if needed"],
        "cost_range": "$100-$900+ depending on diagnosis",
        "mechanic_questions": ["What test points to cylinder 2 specifically?", "Did the coil or plug get swapped to verify the fault?", "Is there any risk of catalytic converter damage if I keep driving?"],
        "category": "engine",
    },
    {
        "code": "P0420",
        "title": "Catalyst System Efficiency Below Threshold",
        "explanation": "Your car may be seeing that the catalytic converter is not cleaning exhaust as expected. It can be caused by a failing converter, but oxygen sensors, exhaust leaks, and engine running problems should be checked too.",
        "urgency": "moderate",
        "drive_safety": "caution",
        "likely_causes": ["Aging catalytic converter", "Oxygen sensor issue", "Exhaust leak", "Misfire or rich/lean running condition", "Aftermarket converter mismatch"],
        "repair_paths": ["Check for exhaust leaks", "Review oxygen sensor live data", "Fix misfires or fuel trim problems first", "Replace catalytic converter only after confirming upstream causes"],
        "cost_range": "$150-$2,500+ depending on sensor vs converter",
        "mechanic_questions": ["Can you show upstream and downstream oxygen sensor data?", "Were exhaust leaks checked?", "Are there other engine codes that should be fixed first?"],
        "category": "emissions",
    },
    {
        "code": "P0171",
        "title": "System Too Lean - Bank 1",
        "explanation": "Your engine may be getting too much air or not enough fuel on bank 1. This often points to an air leak, dirty sensor, weak fuel delivery, or exhaust leak affecting sensor readings.",
        "urgency": "moderate",
        "drive_safety": "caution",
        "likely_causes": ["Vacuum leak", "Dirty or faulty mass airflow sensor", "Weak fuel pump", "Clogged fuel injector", "Exhaust leak before oxygen sensor"],
        "repair_paths": ["Smoke test intake for leaks", "Clean or test MAF sensor", "Check fuel trims and fuel pressure", "Inspect PCV hoses and intake boots"],
        "cost_range": "$90-$800+ depending on leak or fuel issue",
        "mechanic_questions": ["What are the short-term and long-term fuel trims?", "Was a smoke test performed?", "Did you test fuel pressure before recommending parts?"],
        "category": "fuel_air",
    },
    {
        "code": "P0455",
        "title": "Evaporative Emission System Large Leak",
        "explanation": "Your car may have a large leak in the fuel vapor system. This is often not an immediate driving danger, but it can trigger emissions issues and fuel smell concerns.",
        "urgency": "low",
        "drive_safety": "safe",
        "likely_causes": ["Loose or failed gas cap", "Cracked EVAP hose", "Faulty purge valve", "Faulty vent valve", "Damaged charcoal canister"],
        "repair_paths": ["Check gas cap seal", "Run EVAP smoke test", "Test purge and vent valves", "Inspect canister and vapor lines"],
        "cost_range": "$20-$650 depending on cap, valve, or leak location",
        "mechanic_questions": ["Was the gas cap seal checked first?", "Can you show where the smoke test found the leak?", "Which EVAP valve failed testing?"],
        "category": "emissions",
    },
    {
        "code": "P0442",
        "title": "Evaporative Emission System Small Leak",
        "explanation": "Your car may have a small vapor leak in the EVAP system. It is commonly related to the gas cap, small hoses, or EVAP valves.",
        "urgency": "low",
        "drive_safety": "safe",
        "likely_causes": ["Loose gas cap", "Small cracked EVAP hose", "Purge valve leak", "Vent valve issue", "Fuel filler neck seal issue"],
        "repair_paths": ["Reseat or replace gas cap", "Smoke test EVAP system", "Test purge and vent valves", "Inspect filler neck and hoses"],
        "cost_range": "$20-$500 depending on leak source",
        "mechanic_questions": ["Did a smoke test confirm the leak?", "Is the gas cap OEM or aftermarket?", "Which component failed a test rather than just being suspected?"],
        "category": "emissions",
    },
    {
        "code": "P0128",
        "title": "Coolant Thermostat Below Regulating Temperature",
        "explanation": "Your engine is taking longer than expected to reach normal operating temperature. A thermostat stuck open is common, but coolant sensor readings and coolant level should also be checked.",
        "urgency": "moderate",
        "drive_safety": "caution",
        "likely_causes": ["Thermostat stuck open", "Low coolant", "Coolant temperature sensor issue", "Wiring problem", "Cold weather with short trips"],
        "repair_paths": ["Verify coolant level", "Compare temperature sensor data to actual temperature", "Replace thermostat if confirmed", "Inspect cooling system for leaks"],
        "cost_range": "$120-$600 depending on thermostat access",
        "mechanic_questions": ["What temperature did the engine reach during testing?", "Was coolant level checked?", "Is the thermostat confirmed stuck open?"],
        "category": "cooling",
    },
    {
        "code": "P0113",
        "title": "Intake Air Temperature Sensor Circuit High",
        "explanation": "Your car is seeing an intake air temperature sensor reading that may be out of range. This can affect fuel calculations and may come from the sensor, connector, or wiring.",
        "urgency": "low",
        "drive_safety": "safe",
        "likely_causes": ["Disconnected IAT sensor", "Faulty IAT sensor", "Damaged wiring", "Corroded connector", "MAF sensor assembly issue"],
        "repair_paths": ["Inspect connector and wiring", "Compare IAT reading to outside temperature when cold", "Replace sensor or MAF assembly if confirmed", "Clear code and retest"],
        "cost_range": "$40-$350 depending on sensor design",
        "mechanic_questions": ["What temperature is the sensor reporting when the engine is cold?", "Is the sensor separate or part of the MAF?", "Was the connector inspected for corrosion?"],
        "category": "sensor",
    },
    {
        "code": "P0010",
        "title": "Camshaft Position Actuator Circuit - Bank 1",
        "explanation": "Your car may have an electrical issue in the camshaft timing actuator circuit. This system helps adjust engine timing, so oil condition, solenoids, and wiring matter.",
        "urgency": "moderate",
        "drive_safety": "caution",
        "likely_causes": ["Faulty VVT solenoid", "Low or dirty oil", "Wiring or connector issue", "Oil sludge", "ECM command issue"],
        "repair_paths": ["Check oil level and condition", "Inspect VVT solenoid connector", "Test solenoid resistance and command", "Replace solenoid if testing confirms"],
        "cost_range": "$120-$700 depending on access and oil condition",
        "mechanic_questions": ["Was oil level and sludge checked?", "Did the solenoid fail an electrical test?", "Can you show the connector or wiring concern?"],
        "category": "engine_timing",
    },
    {
        "code": "P0011",
        "title": "Camshaft Timing Over-Advanced - Bank 1",
        "explanation": "Your engine timing may be more advanced than expected on bank 1. This can be caused by oil flow problems, a sticking VVT solenoid, or timing components.",
        "urgency": "high",
        "drive_safety": "caution",
        "likely_causes": ["Dirty or low oil", "Sticking VVT solenoid", "Timing chain stretch", "Camshaft actuator issue", "Oil control passage restriction"],
        "repair_paths": ["Check oil level and service history", "Test or replace VVT solenoid", "Inspect timing data", "Evaluate timing chain if symptoms are severe"],
        "cost_range": "$150-$1,800+ depending on solenoid vs timing work",
        "mechanic_questions": ["Is the oil level correct and clean?", "Was the VVT solenoid tested?", "What data supports timing chain work?"],
        "category": "engine_timing",
    },
    {
        "code": "P0021",
        "title": "Camshaft Timing Over-Advanced - Bank 2",
        "explanation": "Your engine timing may be more advanced than expected on bank 2. Similar to bank 1 timing issues, oil quality, VVT solenoids, and timing components should be checked carefully.",
        "urgency": "high",
        "drive_safety": "caution",
        "likely_causes": ["Dirty or low oil", "Bank 2 VVT solenoid issue", "Timing chain wear", "Oil flow restriction", "Cam actuator issue"],
        "repair_paths": ["Check oil and service interval", "Compare bank 1 and bank 2 timing data", "Test VVT solenoid", "Inspect timing components if commanded timing is not responding"],
        "cost_range": "$150-$1,900+ depending on root cause",
        "mechanic_questions": ["How does bank 2 compare to bank 1 in live data?", "Was the solenoid swapped or tested?", "Is timing chain work confirmed by data?"],
        "category": "engine_timing",
    },
    {
        "code": "P0500",
        "title": "Vehicle Speed Sensor",
        "explanation": "Your car may not be receiving a reliable vehicle speed signal. This can affect the speedometer, ABS, transmission shifting, and stability systems depending on the vehicle.",
        "urgency": "moderate",
        "drive_safety": "caution",
        "likely_causes": ["Faulty vehicle speed sensor", "Wheel speed sensor issue", "Damaged wiring", "Transmission output sensor issue", "ABS module signal issue"],
        "repair_paths": ["Confirm speed signal in live data", "Inspect sensor wiring", "Check ABS-related codes", "Replace sensor only after identifying which signal is missing"],
        "cost_range": "$120-$700 depending on sensor and access",
        "mechanic_questions": ["Which speed signal is missing?", "Are there ABS or transmission codes too?", "Was wiring checked before replacing the sensor?"],
        "category": "drivetrain",
    },
    {
        "code": "P0700",
        "title": "Transmission Control System",
        "explanation": "Your car is reporting that the transmission control system has detected a problem. P0700 is often a pointer code, so the transmission module usually needs to be scanned for more specific information.",
        "urgency": "critical",
        "drive_safety": "avoid driving",
        "likely_causes": ["Transmission module stored fault", "Low or contaminated transmission fluid", "Shift solenoid issue", "Wiring problem", "Internal transmission concern"],
        "repair_paths": ["Scan the transmission control module for specific codes", "Check fluid level and condition if serviceable", "Inspect wiring and connectors", "Avoid approving major repairs without specific transmission data"],
        "cost_range": "$150 diagnostic to $3,500+ for major transmission repair",
        "mechanic_questions": ["What are the specific TCM codes behind P0700?", "What does the transmission fluid look like?", "Can you separate electrical, solenoid, and internal failure possibilities?"],
        "category": "transmission",
    },
    {
        "code": "P0141",
        "title": "Oxygen Sensor Heater Circuit - Bank 1 Sensor 2",
        "explanation": "Your car may have a problem with the heater circuit for the downstream oxygen sensor. This sensor helps emissions monitoring and usually does not mean the engine itself is failing.",
        "urgency": "low",
        "drive_safety": "safe",
        "likely_causes": ["Failed downstream oxygen sensor heater", "Blown fuse", "Wiring damage", "Connector corrosion", "Exhaust heat damage"],
        "repair_paths": ["Check heater circuit fuse and power", "Inspect downstream oxygen sensor wiring", "Test heater resistance", "Replace sensor if heater circuit failure is confirmed"],
        "cost_range": "$120-$450 depending on sensor access",
        "mechanic_questions": ["Was heater power and ground checked?", "Is the wiring damaged near the exhaust?", "Is this downstream sensor affecting emissions readiness?"],
        "category": "emissions",
    },
]
